### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by object-Object** [hexdoc-dev/hexdoc#2]
- [x] 3-way merge .gitignore instead of clobbering it
- [x] If root is empty, put latest there so it's not a gross nasty 404
- [x] Document setup command for fish (`. venv/bin/activate.fish`)
- [x] Document hatch-gradle-version, or at least the `tool.hatch.version.key` config option
- [x] Clarify how to use Python 3.11
- [x] Add default values for props, src, dst, etc
- [x] Add nodemon config to cookiecutter
- [x] Clarify the "leave `output_directory` blank" thing
- [x] Use Cruft
- [x] Template parameter for the book id if on 0.10.3
- [x] Replace TODOs with template params
- [x] Non-English lang files are not exported
- [x] Expose all Minecraft assets
- [x] model texture lookup:
  - [x] scrape all the `models/items` files
  - [x] pass blocks through minecraft-render
  - [x] map from itemresourcelocation to full url, mcmeta
- [x] png texture lookup:
  - [x] scrape all the `textures/**/*.png` files
  - [x] somehow get a file list from minecraft-assets via minecraft-render
  - [x] map from texture resloc to full url
- [x] gaslighting items tag
- [x] un-break the CI with the new hexdoc structure
- [x] make hexdoc properly support non-book plugins (ie. itself) - mod version, minecraft version
- [x] hook to add default rendered templates
- [x] pretty sure allow_missing is broken (ie. always true)
- [ ] show GitHub link to whatever commit built the book
- [ ] show Minecraft version
- [ ] allow compatible Minecraft versions
